# Generated by Django 4.2.8 on 2023-12-18 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomerModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_id", models.CharField(max_length=20, unique=True)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("phone_number", models.CharField(max_length=15)),
                ("monthly_salary", models.IntegerField()),
                ("approved_limit", models.IntegerField()),
                ("current_debt", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="LoanModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_id", models.CharField(max_length=20, unique=True)),
                ("loan_id", models.CharField(max_length=20, unique=True)),
                ("loan_amount", models.IntegerField()),
                ("tenure", models.IntegerField()),
                ("interest_rate", models.IntegerField()),
                ("monthly_repayment", models.IntegerField()),
                ("emis_paid_on_time", models.IntegerField(default=0)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
        ),
    ]
