# Generated by Django 4.2.8 on 2023-12-19 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_loanmodel_customer_id"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="loanmodel", unique_together={("customer_id", "loan_id")},
        ),
    ]
