# Generated by Django 4.2.8 on 2023-12-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_loanmodel_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loanmodel",
            name="loan_id",
            field=models.CharField(max_length=20),
        ),
    ]
