# Generated by Django 4.2.8 on 2023-12-19 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_customermodel_age"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customermodel", options={"ordering": ["-customer_id"]},
        ),
    ]
