# Generated by Django 4.2.8 on 2023-12-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_customermodel_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customermodel",
            name="current_debt",
            field=models.IntegerField(default=0),
        ),
    ]
